project:
  type: website
  resources:
    - "covers/*"
    - "game_covers.jpg"

website:
  title: "Video Game Duration"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: story.qmd
        text: Story
      - href: exploration.qmd
        text: Exploration
      - about.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true



